---
- name: Deploy Tenant
  hosts: all
  connection: local
  gather_facts: no
  vars_prompt:
    - name: "tenant"
      prompt: "What would you like to name your Tenant?"
      private: no
  tasks:
    - name: Add a new tenant
      aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('ansible.builtin.env', 'ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('ansible.builtin.env', 'ANSIBLE_NET_PASSWORD') }}"
        tenant: "{{ tenant  }}"
        state: present
      delegate_to: localhost